version: "3.9"

services:
  # database service
  postgresql_db:
    container_name: postgres_container
    image: postgres:latest
    environment:
      - POSTGRES_DATABASE=fxcryptapp
      - POSTGRES_USER=fxcryptapp
      - POSTGRES_PASSWORD=fxcryptapp
    ports:
      - "5432:5432" # map container port 5432 to 5432 on host
    volumes:
      - postgres_data:/data/db

  # admin tool for postgresql db
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=fxcryptapp@fxcryptapp.co.za
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - postgresql_db
    ports:
      - "5433:80" # map container port 80 to 5433 on host
    volumes:
      - pgadmin:/root/.pgadmin

volumes:
  postgres_data:
  pgadmin: